version: '3'
services:
  dojo:
    platform: linux/amd64
    build:  .
    command: lib.py
    volumes:
      - ./patch/lib.py:/app/lib.py
      - ./tmp:/tmp

    environment:
      - parser.id=Checkmarx Scan
      - parser.file=/tmp/timesprime.xml
      - parser.result=/tmp/timesprime.csv


